name: Keep Streamlit App Alive

on:
  schedule:
    # S'exécute toutes les 8 heures (0 0,8,16 * * *)
    - cron: '0 */8 * * *'
  workflow_dispatch: # Permet de lancer le script manuellement pour tester

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Donne le droit à l'action de pousser un commit

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Submettre un commit vide
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.name "github-actions[bot]@://github.com"
        git commit --allow-empty -m "Chrono: Keep Streamlit App Alive"
        git push origin main
